### ISSUE TITLE
delete without filesystem access

### ISSUE THREAD

**Issue by glensc** [glensc/gitlab-registry-cleanup-hook#1]
i've used [docker-ls](https://github.com/mayflower/docker-ls) successfully to delete images without needing filesystem access.

this means it's all doable via registry v2 api calls.

**Comment by morph027** [comment]
Great!

Lately, i was using this tool: https://github.com/n0madic/gitlab-registry-images-cleaner/

**Comment by glensc** [comment]
yay, released in 0.3.0
